# Dependencies
highlighter:      Pygments

gems: [jekyll-paginate,
        jekyll-paginate,
        jekyll-gist,
        redcarpet,
        pygments.rb]

# Permalinks
permalink:        pretty

# Setup
title:            Akash's portfolio
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              /
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5
firstname:         'Akash'
lastname:         'SHETYE'

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
