# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title-bold: Akash Shetye
title-normal: The School of Information @ University of Texas at Austin
email: a(dot)s(at)utexas(dot)edu
description: Graduate student exploring UI/UX fundamentals and research.<br>Looking for Product Management, UX and Front-end internships for Summer 2017.<br/><br/>Ex-Developer Analyst @ Credit Suisse, 2013-2016.<br/><br/>Occaisonal Volunteer Dev @ UN Volunteers<br/><br/>Graduate Research Assistant @ University of Texas Libraries, 2016-Present.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: "https://she1991.github.io" # the base hostname & protocol for your site
author: 
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages" 
tiles-count: 6

# Social settings
500px_url: 
facebook_url: 
github_url: 
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url: 
slack_url: 
twitter_url: https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown

# Plugin: jekyll-seo-tag
twitter:
  username: andrewbanchich
# Add one or more of the following
facebook:
  app_id: 
  publisher: 
  admins: 
logo:
google_site_verification: 
